# Generated by Django 2.1.2 on 2019-02-19 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie2', '0002_auto_20190218_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
