# Generated by Django 2.1.2 on 2019-01-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie1', '0002_auto_20181104_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
